export { LoginPage as Login } from './Login'
export { MainPage as Home } from './Main'
export { ProfilePage as Profile } from './Profile'
export { ErrorPage as Error } from './Error'
export { LeaderboardPage as Leader } from './Leaderboard'
export { ForumPage as Forum } from './Forum/Forum'
export { ThemeBranchPage as ThemeBranch } from './Forum/ThemeBranch'
export { ThemePage as Theme } from './Forum/Themes'
