export { LoginPage as Login } from './Login'
export { SignUpPage as SignUp } from './SignUp'
export { MainPage as Home } from './Main'
export { ProfilePage as Profile } from './Profile'
export { ErrorPage as Error } from './Error'
